"""
ML inference engine for signal generation.

The same MLInferenceEngine class is used in:
    - Notebooks for backtest research (load fold model → predict on test set)
    - Streamlit app for live daily inference (load latest model → signal today)

Zero drift between research and production.

Regression pivot (v2.3):
    - predict() outputs pred_ev (continuous ATR-normalized EV) instead of ml_prob
    - Signals generated by fixed threshold on pred_ev (not probability thresholding)
    - Calibrator removed (was Platt scaling for classification only)
    - rank_signals() ranks by pred_ev instead of ml_prob

Usage:
    from forex_system.models.inference import MLInferenceEngine

    engine = MLInferenceEngine.load_latest("EUR_USD", "H1", "lightgbm")
    result_df = engine.predict(features_df)
    # result_df has added columns: pred_ev, ml_signal
"""

import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from loguru import logger

from forex_system.config import settings
from forex_system.features.builders import FeaturePipeline

ML_FEATURE_COLS: list[str] = FeaturePipeline.ML_FEATURE_COLS


class MLInferenceEngine:
    """
    Loads a trained regression model and generates EV-based directional signals.

    Signal thresholds (fixed-threshold mode):
        pred_ev > +ev_threshold   → ml_signal = 1  (long)
        pred_ev < -ev_threshold   → ml_signal = -1 (short)
        otherwise                 → ml_signal = 0  (flat)

    pred_ev is the model's predicted label_ev: ATR-normalized expected value
    clipped to triple-barrier outcomes. Positive = expected profit, negative =
    expected loss, in units of ATR.

    ev_threshold of 0.05 means "only trade when the model predicts > 5% of ATR
    expected edge". Tune this in notebook 04 based on distribution of pred_ev.

    Ranking mode (use rank_signals()):
        Rank all bars by pred_ev; only top/bottom quartile bars are actionable.
        Preferred when the EV distribution shifts across regimes.
    """

    def __init__(
        self,
        model_path: Path,
        ev_threshold: float = 0.05,
    ) -> None:
        self.ev_threshold = ev_threshold
        with open(model_path, "rb") as fh:
            payload = pickle.load(fh)

        # Support both old format (raw model) and new format (dict)
        if isinstance(payload, dict) and "model" in payload:
            self.model = payload["model"]
        else:
            self.model = payload

        logger.info(
            f"MLInferenceEngine loaded: {model_path.name} "
            f"ev_threshold={ev_threshold}"
        )

    def predict(self, features_df: pd.DataFrame) -> pd.DataFrame:
        """
        Generate ML signals for all rows in features_df.

        Args:
            features_df: DataFrame with ML_FEATURE_COLS columns.
                         Must NOT contain label columns (use include_labels=False).

        Returns:
            Copy of features_df with added columns:
                pred_ev   (float): predicted ATR-normalized expected value
                ml_signal (int):   1, -1, or 0
        """
        valid_mask = features_df[ML_FEATURE_COLS].notna().all(axis=1)
        valid_df = features_df.loc[valid_mask, ML_FEATURE_COLS]

        raw_preds = self.model.predict(valid_df)

        ev_series = pd.Series(raw_preds, index=valid_df.index, name="pred_ev")
        signal_series = pd.Series(0, index=valid_df.index, name="ml_signal")
        signal_series[ev_series > self.ev_threshold] = 1
        signal_series[ev_series < -self.ev_threshold] = -1

        # Deduplicate index (keep last) so reindex on assign does not raise
        ev_series = ev_series[~ev_series.index.duplicated(keep="last")]
        signal_series = signal_series[~signal_series.index.duplicated(keep="last")]

        result = features_df.copy()
        result["pred_ev"] = ev_series

        # CHANGE 5 (v2.4): ML removed from live signal path.
        # The model is contra-predictive (mean Sharpe -1.151 across all 7 pairs).
        # It re-enters the signal path only when shadow-mode IC > 0.06 for
        # 90+ consecutive trading days on both USD_JPY and USD_CHF simultaneously.
        if not settings.ml_enabled:
            if settings.ml_evaluation_mode:
                # Shadow mode: compute the signal the model would have taken, log it
                # for diagnostic analysis, but do NOT act on it.
                n_long  = int((signal_series == 1).sum())
                n_short = int((signal_series == -1).sum())
                mean_ev = float(ev_series.mean()) if len(ev_series) > 0 else float("nan")
                logger.info(
                    "ML_SHADOW | ml_enabled=False | ev_threshold=%.3f | "
                    "mean_pred_ev=%.4f | would_long=%d | would_short=%d | "
                    "Total bars with predictions: %d. "
                    "ML re-enters signal path when IC > 0.06 for 90+ days on "
                    "both USD_JPY and USD_CHF simultaneously.",
                    self.ev_threshold, mean_ev, n_long, n_short, len(ev_series),
                )
            result["ml_signal"] = 0   # never enter signal path
        else:
            result["ml_signal"] = signal_series.reindex(result.index, fill_value=0).astype(int)

        return result

    def rank_signals(
        self,
        features_df: pd.DataFrame,
        top_quantile: float = 0.75,
        min_bars: int = 20,
    ) -> pd.DataFrame:
        """
        Rank-based signal generation (preferred over fixed-threshold when
        the EV distribution shifts across regimes).

        Computes pred_ev for all valid rows, then marks only bars in the top
        (1 - top_quantile) × 100% as long signals and bottom (1 - top_quantile)%
        as short signals. Adapts automatically as the distribution drifts.

        Args:
            features_df:   DataFrame with ML_FEATURE_COLS columns.
            top_quantile:  Percentile cutoff (0.75 → top 25% go long, bottom 25% short).
            min_bars:      Minimum valid rows required to compute ranks (default 20).

        Returns:
            Copy of features_df with added columns:
                pred_ev        (float): predicted ATR-normalized EV
                ml_signal_rank (int):   1 (top quartile), -1 (bottom quartile), 0 (flat)
        """
        result = self.predict(features_df)

        if result["pred_ev"].notna().sum() < min_bars:
            result["ml_signal_rank"] = 0
            return result

        p_high = result["pred_ev"].quantile(top_quantile)
        p_low = result["pred_ev"].quantile(1.0 - top_quantile)

        rank_signal = pd.Series(0, index=result.index, name="ml_signal_rank")
        rank_signal[result["pred_ev"] >= p_high] = 1
        rank_signal[result["pred_ev"] <= p_low] = -1
        result["ml_signal_rank"] = rank_signal
        return result

    @classmethod
    def load_latest(
        cls,
        instrument: str,
        granularity: str,
        model_type: str = "lightgbm",
        ev_threshold: float = 0.05,
    ) -> "MLInferenceEngine":
        """
        Load the highest-numbered fold model for a given instrument/granularity.

        Raises:
            FileNotFoundError if no matching model artifact exists.
        """
        pattern = f"{instrument}_{granularity}_{model_type}_fold*.pkl"
        candidates = sorted(settings.data_artifacts.glob(pattern))

        if not candidates:
            raise FileNotFoundError(
                f"No model found matching '{pattern}' in {settings.data_artifacts}. "
                "Run notebooks/04_ml_training.ipynb first."
            )

        latest = candidates[-1]  # alphabetically last = highest fold number
        return cls(latest, ev_threshold=ev_threshold)

    @classmethod
    def load_fold(
        cls,
        instrument: str,
        granularity: str,
        model_type: str,
        fold_id: int,
        ev_threshold: float = 0.05,
    ) -> "MLInferenceEngine":
        """Load a specific fold model by ID."""
        path = (
            settings.data_artifacts
            / f"{instrument}_{granularity}_{model_type}_fold{fold_id}.pkl"
        )
        if not path.exists():
            raise FileNotFoundError(f"Model not found: {path}")
        return cls(path, ev_threshold=ev_threshold)
